export const INDIAN_BANKS = [
    "State Bank of India",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "IndusInd Bank",
    "Bank of Baroda",
    "Punjab National Bank",
    "Canara Bank",
    "Union Bank of India",
    "Bank of India",
    "Indian Bank",
    "Central Bank of India",
    "IDBI Bank",
    "Yes Bank",
    "UCO Bank",
    "Federal Bank",
    "IDFC FIRST Bank",
    "Standard Chartered Bank",
    "South Indian Bank",
    "RBL Bank",
    "Bandhan Bank",
    "Dhanlaxmi Bank",
    "Karnataka Bank",
    "Karur Vysya Bank",
    "Tamilnad Mercantile Bank",
    "DCB Bank",
    "City Union Bank",
    "J&K Bank",
    "DBS Bank India",
    "Airtel Payments Bank",
    "Paytm Payments Bank",
    "Jio Payments Bank",
    "India Post Payments Bank",
    "Fino Payments Bank",
    "NSDL Payments Bank",
].sort();
