-- Align FarmDetails with schema
ALTER TABLE "FarmDetails"
ADD COLUMN "aadhaarCardImage" TEXT,
ADD COLUMN "bankPassbookImage" TEXT,
ADD COLUMN "satbaraImage" TEXT,
ADD COLUMN "patwariMapImage" TEXT,
ADD COLUMN "landImage1" TEXT,
ADD COLUMN "landImage1Gps" TEXT,
ADD COLUMN "landImage2" TEXT,
ADD COLUMN "landImage2Gps" TEXT,
ADD COLUMN "landImage3" TEXT,
ADD COLUMN "landImage3Gps" TEXT,
ADD COLUMN "landImage4" TEXT,
ADD COLUMN "landImage4Gps" TEXT,
ADD COLUMN "landImage5" TEXT,
ADD COLUMN "landImage5Gps" TEXT,
ADD COLUMN "landImage6" TEXT,
ADD COLUMN "landImage6Gps" TEXT,
ADD COLUMN "landImage7" TEXT,
ADD COLUMN "landImage7Gps" TEXT,
ADD COLUMN "landImage8" TEXT,
ADD COLUMN "landImage8Gps" TEXT;
